export const KYUSHU_MUNICIPALITY_SOURCE = {
  "福岡県": [
    { name: "門司区", kana: "もじく", code: "40101", parent: "北九州市" },
    { name: "若松区", kana: "わかまつく", code: "40103", parent: "北九州市" },
    { name: "戸畑区", kana: "とばたく", code: "40105", parent: "北九州市" },
    { name: "小倉北区", kana: "こくらきたく", code: "40106", parent: "北九州市" },
    { name: "小倉南区", kana: "こくらみなみく", code: "40107", parent: "北九州市" },
    { name: "八幡東区", kana: "やはたひがしく", code: "40108", parent: "北九州市" },
    { name: "八幡西区", kana: "やはたにしく", code: "40109", parent: "北九州市" },
    { name: "東区", kana: "ひがしく", code: "40131", parent: "福岡市" },
    { name: "博多区", kana: "はかたく", code: "40132", parent: "福岡市" },
    { name: "中央区", kana: "ちゅうおうく", code: "40133", parent: "福岡市" },
    { name: "南区", kana: "みなみく", code: "40134", parent: "福岡市" },
    { name: "西区", kana: "にしく", code: "40135", parent: "福岡市" },
    { name: "城南区", kana: "じょうなんく", code: "40136", parent: "福岡市" },
    { name: "早良区", kana: "さわらく", code: "40137", parent: "福岡市" },
    { name: "大牟田市", kana: "おおむたし", code: "40202" },
    { name: "久留米市", kana: "くるめし", code: "40203" },
    { name: "直方市", kana: "のおがたし", code: "40204" },
    { name: "飯塚市", kana: "いいづかし", code: "40205" },
    { name: "田川市", kana: "たがわし", code: "40206" },
    { name: "柳川市", kana: "やながわし", code: "40207" },
    { name: "八女市", kana: "やめし", code: "40210" },
    { name: "筑後市", kana: "ちくごし", code: "40211" },
    { name: "大川市", kana: "おおかわし", code: "40212" },
    { name: "行橋市", kana: "ゆくはしし", code: "40213" },
    { name: "豊前市", kana: "ぶぜんし", code: "40214" },
    { name: "中間市", kana: "なかまし", code: "40215" },
    { name: "小郡市", kana: "おごおりし", code: "40216" },
    { name: "筑紫野市", kana: "ちくしのし", code: "40217" },
    { name: "春日市", kana: "かすがし", code: "40218" },
    { name: "大野城市", kana: "おおのじょうし", code: "40219" },
    { name: "宗像市", kana: "むなかたし", code: "40220" },
    { name: "太宰府市", kana: "だざいふし", code: "40221" },
    { name: "古賀市", kana: "こがし", code: "40223" },
    { name: "福津市", kana: "ふくつし", code: "40224" },
    { name: "うきは市", kana: "うきはし", code: "40225" },
    { name: "宮若市", kana: "みやわかし", code: "40226" },
    { name: "嘉麻市", kana: "かまし", code: "40227" },
    { name: "朝倉市", kana: "あさくらし", code: "40228" },
    { name: "みやま市", kana: "みやまし", code: "40229" },
    { name: "糸島市", kana: "いとしまし", code: "40230" },
    { name: "那珂川市", kana: "なかがわし", code: "40231" },
    { name: "宇美町", kana: "うみまち", code: "40341", parent: "糟屋郡" },
    { name: "篠栗町", kana: "ささぐりまち", code: "40342", parent: "糟屋郡" },
    { name: "志免町", kana: "しめまち", code: "40343", parent: "糟屋郡" },
    { name: "須恵町", kana: "すえまち", code: "40344", parent: "糟屋郡" },
    { name: "新宮町", kana: "しんぐうまち", code: "40345", parent: "糟屋郡" },
    { name: "久山町", kana: "ひさやままち", code: "40348", parent: "糟屋郡" },
    { name: "粕屋町", kana: "かすやまち", code: "40349", parent: "糟屋郡" },
    { name: "芦屋町", kana: "あしやまち", code: "40381", parent: "遠賀郡" },
    { name: "水巻町", kana: "みずまきまち", code: "40382", parent: "遠賀郡" },
    { name: "岡垣町", kana: "おかがきまち", code: "40383", parent: "遠賀郡" },
    { name: "遠賀町", kana: "おんがちょう", code: "40384", parent: "遠賀郡" },
    { name: "小竹町", kana: "こたけまち", code: "40401", parent: "鞍手郡" },
    { name: "鞍手町", kana: "くらてまち", code: "40402", parent: "鞍手郡" },
    { name: "桂川町", kana: "けいせんまち", code: "40421", parent: "嘉穂郡" },
    { name: "筑前町", kana: "ちくぜんまち", code: "40447", parent: "朝倉郡" },
    { name: "東峰村", kana: "とうほうむら", code: "40448", parent: "朝倉郡" },
    { name: "大刀洗町", kana: "たちあらいまち", code: "40503", parent: "三井郡" },
    { name: "大木町", kana: "おおきまち", code: "40522", parent: "三潴郡" },
    { name: "広川町", kana: "ひろかわまち", code: "40544", parent: "八女郡" },
    { name: "香春町", kana: "かわらまち", code: "40601", parent: "田川郡" },
    { name: "添田町", kana: "そえだまち", code: "40602", parent: "田川郡" },
    { name: "糸田町", kana: "いとだまち", code: "40604", parent: "田川郡" },
    { name: "川崎町", kana: "かわさきまち", code: "40605", parent: "田川郡" },
    { name: "大任町", kana: "おおとうまち", code: "40608", parent: "田川郡" },
    { name: "赤村", kana: "あかむら", code: "40609", parent: "田川郡" },
    { name: "福智町", kana: "ふくちまち", code: "40610", parent: "田川郡" },
    { name: "苅田町", kana: "かんだまち", code: "40621", parent: "京都郡" },
    { name: "みやこ町", kana: "みやこまち", code: "40625", parent: "京都郡" },
    { name: "吉富町", kana: "よしとみまち", code: "40642", parent: "築上郡" },
    { name: "上毛町", kana: "こうげまち", code: "40646", parent: "築上郡" },
    { name: "築上町", kana: "ちくじょうまち", code: "40647", parent: "築上郡" }
  ],
  "佐賀県": [
    { name: "佐賀市", kana: "さがし", code: "41201" },
    { name: "唐津市", kana: "からつし", code: "41202" },
    { name: "鳥栖市", kana: "とすし", code: "41203" },
    { name: "多久市", kana: "たくし", code: "41204" },
    { name: "伊万里市", kana: "いまりし", code: "41205" },
    { name: "武雄市", kana: "たけおし", code: "41206" },
    { name: "鹿島市", kana: "かしまし", code: "41207" },
    { name: "小城市", kana: "おぎし", code: "41208" },
    { name: "嬉野市", kana: "うれしのし", code: "41209" },
    { name: "神埼市", kana: "かんざきし", code: "41210" },
    { name: "吉野ヶ里町", kana: "よしのがりちょう", code: "41327", parent: "神埼郡" },
    { name: "基山町", kana: "きやまちょう", code: "41341", parent: "三養基郡" },
    { name: "上峰町", kana: "かみみねちょう", code: "41345", parent: "三養基郡" },
    { name: "みやき町", kana: "みやきちょう", code: "41346", parent: "三養基郡" },
    { name: "玄海町", kana: "げんかいちょう", code: "41387", parent: "東松浦郡" },
    { name: "有田町", kana: "ありたちょう", code: "41401", parent: "西松浦郡" },
    { name: "大町町", kana: "おおまちちょう", code: "41423", parent: "杵島郡" },
    { name: "江北町", kana: "こうほくまち", code: "41424", parent: "杵島郡" },
    { name: "白石町", kana: "しろいしちょう", code: "41425", parent: "杵島郡" },
    { name: "太良町", kana: "たらちょう", code: "41441", parent: "藤津郡" }
  ],
  "長崎県": [
    { name: "長崎市", kana: "ながさきし", code: "42201" },
    { name: "佐世保市", kana: "させぼし", code: "42202" },
    { name: "島原市", kana: "しまばらし", code: "42203" },
    { name: "諫早市", kana: "いさはやし", code: "42204" },
    { name: "大村市", kana: "おおむらし", code: "42205" },
    { name: "平戸市", kana: "ひらどし", code: "42207" },
    { name: "松浦市", kana: "まつうらし", code: "42208" },
    { name: "対馬市", kana: "つしまし", code: "42209" },
    { name: "壱岐市", kana: "いきし", code: "42210" },
    { name: "五島市", kana: "ごとうし", code: "42211" },
    { name: "西海市", kana: "さいかいし", code: "42212" },
    { name: "雲仙市", kana: "うんぜんし", code: "42213" },
    { name: "南島原市", kana: "みなみしまばらし", code: "42214" },
    { name: "長与町", kana: "ながよちょう", code: "42307", parent: "西彼杵郡" },
    { name: "時津町", kana: "とぎつちょう", code: "42308", parent: "西彼杵郡" },
    { name: "東彼杵町", kana: "ひがしそのぎちょう", code: "42321", parent: "東彼杵郡" },
    { name: "川棚町", kana: "かわたなちょう", code: "42322", parent: "東彼杵郡" },
    { name: "波佐見町", kana: "はさみちょう", code: "42323", parent: "東彼杵郡" },
    { name: "小値賀町", kana: "おぢかちょう", code: "42383", parent: "北松浦郡" },
    { name: "佐々町", kana: "さざちょう", code: "42391", parent: "北松浦郡" },
    { name: "新上五島町", kana: "しんかみごとうちょう", code: "42411", parent: "南松浦郡" }
  ],
  "熊本県": [
    { name: "中央区", kana: "ちゅうおうく", code: "43101", parent: "熊本市" },
    { name: "東区", kana: "ひがしく", code: "43102", parent: "熊本市" },
    { name: "西区", kana: "にしく", code: "43103", parent: "熊本市" },
    { name: "南区", kana: "みなみく", code: "43104", parent: "熊本市" },
    { name: "北区", kana: "きたく", code: "43105", parent: "熊本市" },
    { name: "八代市", kana: "やつしろし", code: "43202" },
    { name: "人吉市", kana: "ひとよしし", code: "43203" },
    { name: "荒尾市", kana: "あらおし", code: "43204" },
    { name: "水俣市", kana: "みなまたし", code: "43205" },
    { name: "玉名市", kana: "たまなし", code: "43206" },
    { name: "山鹿市", kana: "やまがし", code: "43208" },
    { name: "菊池市", kana: "きくちし", code: "43210" },
    { name: "宇土市", kana: "うとし", code: "43211" },
    { name: "上天草市", kana: "かみあまくさし", code: "43212" },
    { name: "宇城市", kana: "うきし", code: "43213" },
    { name: "阿蘇市", kana: "あそし", code: "43214" },
    { name: "天草市", kana: "あまくさし", code: "43215" },
    { name: "合志市", kana: "こうしし", code: "43216" },
    { name: "美里町", kana: "みさとまち", code: "43348", parent: "下益城郡" },
    { name: "玉東町", kana: "ぎょくとうまち", code: "43364", parent: "玉名郡" },
    { name: "南関町", kana: "なんかんまち", code: "43367", parent: "玉名郡" },
    { name: "長洲町", kana: "ながすまち", code: "43368", parent: "玉名郡" },
    { name: "和水町", kana: "なごみまち", code: "43369", parent: "玉名郡" },
    { name: "大津町", kana: "おおづまち", code: "43403", parent: "菊池郡" },
    { name: "菊陽町", kana: "きくようまち", code: "43404", parent: "菊池郡" },
    { name: "南小国町", kana: "みなみおぐにまち", code: "43423", parent: "阿蘇郡" },
    { name: "小国町", kana: "おぐにまち", code: "43424", parent: "阿蘇郡" },
    { name: "産山村", kana: "うぶやまむら", code: "43425", parent: "阿蘇郡" },
    { name: "高森町", kana: "たかもりまち", code: "43428", parent: "阿蘇郡" },
    { name: "西原村", kana: "にしはらむら", code: "43432", parent: "阿蘇郡" },
    { name: "南阿蘇村", kana: "みなみあそむら", code: "43433", parent: "阿蘇郡" },
    { name: "御船町", kana: "みふねまち", code: "43441", parent: "上益城郡" },
    { name: "嘉島町", kana: "かしままち", code: "43442", parent: "上益城郡" },
    { name: "益城町", kana: "ましきまち", code: "43443", parent: "上益城郡" },
    { name: "甲佐町", kana: "こうさまち", code: "43444", parent: "上益城郡" },
    { name: "山都町", kana: "やまとちょう", code: "43447", parent: "上益城郡" },
    { name: "氷川町", kana: "ひかわちょう", code: "43468", parent: "八代郡" },
    { name: "芦北町", kana: "あしきたまち", code: "43482", parent: "葦北郡" },
    { name: "津奈木町", kana: "つなぎまち", code: "43484", parent: "葦北郡" },
    { name: "錦町", kana: "にしきまち", code: "43501", parent: "球磨郡" },
    { name: "多良木町", kana: "たらぎまち", code: "43505", parent: "球磨郡" },
    { name: "湯前町", kana: "ゆのまえまち", code: "43506", parent: "球磨郡" },
    { name: "水上村", kana: "みずかみむら", code: "43507", parent: "球磨郡" },
    { name: "相良村", kana: "さがらむら", code: "43510", parent: "球磨郡" },
    { name: "五木村", kana: "いつきむら", code: "43511", parent: "球磨郡" },
    { name: "山江村", kana: "やまえむら", code: "43512", parent: "球磨郡" },
    { name: "球磨村", kana: "くまむら", code: "43513", parent: "球磨郡" },
    { name: "あさぎり町", kana: "あさぎりちょう", code: "43514", parent: "球磨郡" },
    { name: "苓北町", kana: "れいほくまち", code: "43531", parent: "天草郡" }
  ],
  "大分県": [
    { name: "大分市", kana: "おおいたし", code: "44201" },
    { name: "別府市", kana: "べっぷし", code: "44202" },
    { name: "中津市", kana: "なかつし", code: "44203" },
    { name: "日田市", kana: "ひたし", code: "44204" },
    { name: "佐伯市", kana: "さいきし", code: "44205" },
    { name: "臼杵市", kana: "うすきし", code: "44206" },
    { name: "津久見市", kana: "つくみし", code: "44207" },
    { name: "竹田市", kana: "たけたし", code: "44208" },
    { name: "豊後高田市", kana: "ぶんごたかだし", code: "44209" },
    { name: "杵築市", kana: "きつきし", code: "44210" },
    { name: "宇佐市", kana: "うさし", code: "44211" },
    { name: "豊後大野市", kana: "ぶんごおおのし", code: "44212" },
    { name: "由布市", kana: "ゆふし", code: "44213" },
    { name: "国東市", kana: "くにさきし", code: "44214" },
    { name: "姫島村", kana: "ひめしまむら", code: "44322", parent: "東国東郡" },
    { name: "日出町", kana: "ひじまち", code: "44341", parent: "速見郡" },
    { name: "九重町", kana: "ここのえまち", code: "44461", parent: "玖珠郡" },
    { name: "玖珠町", kana: "くすまち", code: "44462", parent: "玖珠郡" }
  ],
  "宮崎県": [
    { name: "宮崎市", kana: "みやざきし", code: "45201" },
    { name: "都城市", kana: "みやこのじょうし", code: "45202" },
    { name: "延岡市", kana: "のべおかし", code: "45203" },
    { name: "日南市", kana: "にちなんし", code: "45204" },
    { name: "小林市", kana: "こばやしし", code: "45205" },
    { name: "日向市", kana: "ひゅうがし", code: "45206" },
    { name: "串間市", kana: "くしまし", code: "45207" },
    { name: "西都市", kana: "さいとし", code: "45208" },
    { name: "えびの市", kana: "えびのし", code: "45209" },
    { name: "三股町", kana: "みまたちょう", code: "45341", parent: "北諸県郡" },
    { name: "高原町", kana: "たかはるちょう", code: "45361", parent: "西諸県郡" },
    { name: "国富町", kana: "くにとみちょう", code: "45382", parent: "東諸県郡" },
    { name: "綾町", kana: "あやちょう", code: "45383", parent: "東諸県郡" },
    { name: "高鍋町", kana: "たかなべちょう", code: "45401", parent: "児湯郡" },
    { name: "新富町", kana: "しんとみちょう", code: "45402", parent: "児湯郡" },
    { name: "西米良村", kana: "にしめらそん", code: "45403", parent: "児湯郡" },
    { name: "木城町", kana: "きじょうちょう", code: "45404", parent: "児湯郡" },
    { name: "川南町", kana: "かわみなみちょう", code: "45405", parent: "児湯郡" },
    { name: "都農町", kana: "つのちょう", code: "45406", parent: "児湯郡" },
    { name: "門川町", kana: "かどがわちょう", code: "45421", parent: "東臼杵郡" },
    { name: "諸塚村", kana: "もろつかそん", code: "45429", parent: "東臼杵郡" },
    { name: "椎葉村", kana: "しいばそん", code: "45430", parent: "東臼杵郡" },
    { name: "美郷町", kana: "みさとちょう", code: "45431", parent: "東臼杵郡" },
    { name: "高千穂町", kana: "たかちほちょう", code: "45441", parent: "西臼杵郡" },
    { name: "日之影町", kana: "ひのかげちょう", code: "45442", parent: "西臼杵郡" },
    { name: "五ヶ瀬町", kana: "ごかせちょう", code: "45443", parent: "西臼杵郡" }
  ],
  "鹿児島県": [
    { name: "鹿児島市", kana: "かごしまし", code: "46201" },
    { name: "鹿屋市", kana: "かのやし", code: "46203" },
    { name: "枕崎市", kana: "まくらざきし", code: "46204" },
    { name: "阿久根市", kana: "あくねし", code: "46206" },
    { name: "出水市", kana: "いずみし", code: "46208" },
    { name: "指宿市", kana: "いぶすきし", code: "46210" },
    { name: "西之表市", kana: "にしのおもてし", code: "46213" },
    { name: "垂水市", kana: "たるみずし", code: "46214" },
    { name: "薩摩川内市", kana: "さつませんだいし", code: "46215" },
    { name: "日置市", kana: "ひおきし", code: "46216" },
    { name: "曽於市", kana: "そおし", code: "46217" },
    { name: "霧島市", kana: "きりしまし", code: "46218" },
    { name: "いちき串木野市", kana: "いちきくしきのし", code: "46219" },
    { name: "南さつま市", kana: "みなみさつまし", code: "46220" },
    { name: "志布志市", kana: "しぶしし", code: "46221" },
    { name: "奄美市", kana: "あまみし", code: "46222" },
    { name: "南九州市", kana: "みなみきゅうしゅうし", code: "46223" },
    { name: "伊佐市", kana: "いさし", code: "46224" },
    { name: "姶良市", kana: "あいらし", code: "46225" },
    { name: "三島村", kana: "みしまむら", code: "46303", parent: "鹿児島郡" },
    { name: "十島村", kana: "としまむら", code: "46304", parent: "鹿児島郡" },
    { name: "さつま町", kana: "さつまちょう", code: "46392", parent: "薩摩郡" },
    { name: "長島町", kana: "ながしまちょう", code: "46404", parent: "出水郡" },
    { name: "湧水町", kana: "ゆうすいちょう", code: "46452", parent: "姶良郡" },
    { name: "大崎町", kana: "おおさきちょう", code: "46468", parent: "曽於郡" },
    { name: "東串良町", kana: "ひがしくしらちょう", code: "46482", parent: "肝属郡" },
    { name: "錦江町", kana: "きんこうちょう", code: "46490", parent: "肝属郡" },
    { name: "南大隅町", kana: "みなみおおすみちょう", code: "46491", parent: "肝属郡" },
    { name: "肝付町", kana: "きもつきちょう", code: "46492", parent: "肝属郡" },
    { name: "中種子町", kana: "なかたねちょう", code: "46501", parent: "熊毛郡" },
    { name: "南種子町", kana: "みなみたねちょう", code: "46502", parent: "熊毛郡" },
    { name: "屋久島町", kana: "やくしまちょう", code: "46505", parent: "熊毛郡" },
    { name: "大和村", kana: "やまとそん", code: "46523", parent: "大島郡" },
    { name: "宇検村", kana: "うけんそん", code: "46524", parent: "大島郡" },
    { name: "瀬戸内町", kana: "せとうちちょう", code: "46525", parent: "大島郡" },
    { name: "龍郷町", kana: "たつごうちょう", code: "46527", parent: "大島郡" },
    { name: "喜界町", kana: "きかいちょう", code: "46529", parent: "大島郡" },
    { name: "徳之島町", kana: "とくのしまちょう", code: "46530", parent: "大島郡" },
    { name: "天城町", kana: "あまぎちょう", code: "46531", parent: "大島郡" },
    { name: "伊仙町", kana: "いせんちょう", code: "46532", parent: "大島郡" },
    { name: "和泊町", kana: "わどまりちょう", code: "46533", parent: "大島郡" },
    { name: "知名町", kana: "ちなちょう", code: "46534", parent: "大島郡" },
    { name: "与論町", kana: "よろんちょう", code: "46535", parent: "大島郡" }
  ],
  "沖縄県": [
    { name: "那覇市", kana: "なはし", code: "47201" },
    { name: "宜野湾市", kana: "ぎのわんし", code: "47205" },
    { name: "石垣市", kana: "いしがきし", code: "47207" },
    { name: "浦添市", kana: "うらそえし", code: "47208" },
    { name: "名護市", kana: "なごし", code: "47209" },
    { name: "糸満市", kana: "いとまんし", code: "47210" },
    { name: "沖縄市", kana: "おきなわし", code: "47211" },
    { name: "豊見城市", kana: "とみぐすくし", code: "47212" },
    { name: "うるま市", kana: "うるまし", code: "47213" },
    { name: "宮古島市", kana: "みやこじまし", code: "47214" },
    { name: "南城市", kana: "なんじょうし", code: "47215" },
    { name: "国頭村", kana: "くにがみそん", code: "47301", parent: "国頭郡" },
    { name: "大宜味村", kana: "おおぎみそん", code: "47302", parent: "国頭郡" },
    { name: "東村", kana: "ひがしそん", code: "47303", parent: "国頭郡" },
    { name: "今帰仁村", kana: "なきじんそん", code: "47306", parent: "国頭郡" },
    { name: "本部町", kana: "もとぶちょう", code: "47308", parent: "国頭郡" },
    { name: "恩納村", kana: "おんなそん", code: "47311", parent: "国頭郡" },
    { name: "宜野座村", kana: "ぎのざそん", code: "47313", parent: "国頭郡" },
    { name: "金武町", kana: "きんちょう", code: "47314", parent: "国頭郡" },
    { name: "伊江村", kana: "いえそん", code: "47315", parent: "国頭郡" },
    { name: "読谷村", kana: "よみたんそん", code: "47324", parent: "中頭郡" },
    { name: "嘉手納町", kana: "かでなちょう", code: "47325", parent: "中頭郡" },
    { name: "北谷町", kana: "ちゃたんちょう", code: "47326", parent: "中頭郡" },
    { name: "北中城村", kana: "きたなかぐすくそん", code: "47327", parent: "中頭郡" },
    { name: "中城村", kana: "なかぐすくそん", code: "47328", parent: "中頭郡" },
    { name: "西原町", kana: "にしはらちょう", code: "47329", parent: "中頭郡" },
    { name: "与那原町", kana: "よなばるちょう", code: "47348", parent: "島尻郡" },
    { name: "南風原町", kana: "はえばるちょう", code: "47350", parent: "島尻郡" },
    { name: "渡嘉敷村", kana: "とかしきそん", code: "47353", parent: "島尻郡" },
    { name: "座間味村", kana: "ざまみそん", code: "47354", parent: "島尻郡" },
    { name: "粟国村", kana: "あぐにそん", code: "47355", parent: "島尻郡" },
    { name: "渡名喜村", kana: "となきそん", code: "47356", parent: "島尻郡" },
    { name: "南大東村", kana: "みなみだいとうそん", code: "47357", parent: "島尻郡" },
    { name: "北大東村", kana: "きただいとうそん", code: "47358", parent: "島尻郡" },
    { name: "伊平屋村", kana: "いへやそん", code: "47359", parent: "島尻郡" },
    { name: "伊是名村", kana: "いぜなそん", code: "47360", parent: "島尻郡" },
    { name: "久米島町", kana: "くめじまちょう", code: "47361", parent: "島尻郡" },
    { name: "八重瀬町", kana: "やえせちょう", code: "47362", parent: "島尻郡" },
    { name: "多良間村", kana: "たらまそん", code: "47375", parent: "宮古郡" },
    { name: "竹富町", kana: "たけとみちょう", code: "47381", parent: "八重山郡" },
    { name: "与那国町", kana: "よなぐにちょう", code: "47382", parent: "八重山郡" }
  ]
};
